### ISSUE TITLE
AESLua fails to work and fails tests on CC 1.74

### ISSUE THREAD

**Issue by sjennison** [SquidDev-CC/aeslua#11]
AESLua fails to work (decryption is unsuccessful) and also fails Howl tests when run on a CC 1.74 installation (DW20 based).

Here's a partial result of running tests - I can try to get more, but it's outputting to a monitor...

![image](https://cloud.githubusercontent.com/assets/5776850/17724426/0f6ee838-6410-11e6-9737-57aa2c5c6236.png)

**Comment by SquidDev** [comment]
IIRC there was a bug in 1.74 which 1.75 fixed. If you replace the bit library with [https://github.com/SquidDev-CC/aeslua/blob/370bf1649e7f5896fa9c5702e629aec1814c6f47/lib/bit.lua](this one) it should be fine, though you'll take a performance hit.

**Comment by sjennison** [comment]
Forgot to respond to this - thanks! That works great!
